config/routes.rb
Rails.application.routes.draw do
  resources :dialogues
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "dialogues#index"
  resources :episode_texts, only: [:index, :show]
  resources :quotes, only: [:index, :show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dialogue.rb
class Dialogue < ApplicationRecord
    scope :search, -> (query, conn){ select("dialogues.*, ts_rank_cd(dialogues.searchable, websearch_to_tsquery('simple',
       #{conn.quote(query)})) as rank").where("dialogues.searchable @@ websearch_to_tsquery('simple', ?)", query).order('rank DESC')}
    scope :search_english, -> (query, conn){ select("dialogues.*, ts_rank_cd(dialogues.searchable_english, websearch_to_tsquery('english',
        #{conn.quote(query)})) as rank").where("dialogues.searchable_english @@ websearch_to_tsquery('english', ?)", query).order('rank DESC')}
end

app/models/episode_text.rb
class EpisodeText < ApplicationRecord
end

app/models/quote.rb
class Quote < ApplicationRecord
    include PgSearch::Model
    conn = ActiveRecord::Base.connection
     scope :search, -> (query){ select("quotes.*, ts_rank_cd(quotes.searchable, websearch_to_tsquery('simple',
        #{conn.quote(query)})) as rank").where("quotes.searchable @@ websearch_to_tsquery('simple', ?)", query).order('rank DESC')}
     
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dialogues_controller.rb
class DialoguesController < ApplicationController
  before_action :set_dialogue, only: %i[ show edit update destroy ]

  # GET /dialogues or /dialogues.json
  def index
    conn = ActiveRecord::Base.connection
    if params[:dictionary] == "1"
      @dialogues = Dialogue.search_english(params[:query], conn).limit(300)
    else
      @dialogues = Dialogue.search(params[:query], conn).limit(300)
    end
  end

  # GET /dialogues/1 or /dialogues/1.json
  def show
    @dialogue = Dialogue.find(params[:id])
    @text = EpisodeText.where(episode: @dialogue.episode, series: @dialogue.series).first().text
    @with_highlights = @text.gsub("#{@dialogue.character}: #{@dialogue.line}", "<span id=#{@dialogue.id} class=\"highlighted\">#{@dialogue.character}: #{@dialogue.line}</span>")
  end

  # GET /dialogues/new
  def new
    @dialogue = Dialogue.new
  end

  # GET /dialogues/1/edit
  def edit
  end

  # POST /dialogues or /dialogues.json
  def create
    @dialogue = Dialogue.new(dialogue_params)

    respond_to do |format|
      if @dialogue.save
        format.html { redirect_to dialogue_url(@dialogue), notice: "Dialogue was successfully created." }
        format.json { render :show, status: :created, location: @dialogue }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dialogue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dialogues/1 or /dialogues/1.json
  def update
    respond_to do |format|
      if @dialogue.update(dialogue_params)
        format.html { redirect_to dialogue_url(@dialogue), notice: "Dialogue was successfully updated." }
        format.json { render :show, status: :ok, location: @dialogue }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dialogue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dialogues/1 or /dialogues/1.json
  def destroy
    @dialogue.destroy

    respond_to do |format|
      format.html { redirect_to dialogues_url, notice: "Dialogue was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dialogue
      @dialogue = Dialogue.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dialogue_params
      params.require(:dialogue).permit(:line, :episode, :series, :character)
    end
end

app/controllers/episode_texts_controller.rb
require 'net/http'
require 'json'


class EpisodeTextsController < ApplicationController
  
    # GET /dialogues or /dialogues.json
    def index
      uri = URI('http://0.0.0.0')
      hostname = uri.hostname # => "example.com"
      uri.path = '/query'
      query = params[:query]
      @results = []
      if query 
        req = Net::HTTP::Post.new(uri) # => #<Net::HTTP::Post POST>
        req["Authorization"] = "Bearer #{ENV["DOCUMENT_RETRIEVAL_TOKEN"]}"
        req.body = {
            "queries": [{"query": query, "top_k": 10}],
        }.to_json
      
        req.content_type = 'application/json'
        res = Net::HTTP.start(hostname, 8000) do |http|
               http.request(req)
              
        end
        response = JSON.parse(res.body)
        puts response
        @results = response["results"][0]["results"].select{|result| result["score"] < 0.21}
      end
    end
  
    # GET /dialogues/1 or /dialogues/1.json
    def show
      episode = EpisodeText.find(params[:id])
      @episode_text = episode.text
    end
  
    # GET /dialogues/new
    def new
      @dialogue = Dialogue.new
    end
  
    # GET /dialogues/1/edit
    def edit
    end
  
    # POST /dialogues or /dialogues.json
    def create
      @dialogue = Dialogue.new(dialogue_params)
  
      respond_to do |format|
        if @dialogue.save
          format.html { redirect_to dialogue_url(@dialogue), notice: "Dialogue was successfully created." }
          format.json { render :show, status: :created, location: @dialogue }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @dialogue.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /dialogues/1 or /dialogues/1.json
    def update
      respond_to do |format|
        if @dialogue.update(dialogue_params)
          format.html { redirect_to dialogue_url(@dialogue), notice: "Dialogue was successfully updated." }
          format.json { render :show, status: :ok, location: @dialogue }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @dialogue.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /dialogues/1 or /dialogues/1.json
    def destroy
      @dialogue.destroy
  
      respond_to do |format|
        format.html { redirect_to dialogues_url, notice: "Dialogue was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
  
      # Only allow a list of trusted parameters through.
      def dialogue_params
        params.require(:dialogue).permit(:line, :episode, :series, :character)
      end
  end
  

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController

        def index
            @quotes = Quote.search(params[:query]).limit(100)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dialogues_helper.rb
module DialoguesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/dialogues/_dialogue.html.erb
<div id="<%= dom_id dialogue %>">
  <p>
    <strong>Line:</strong>
    <%= dialogue.line %>
  </p>

  <p>
    <strong>Episode:</strong>
    <%= dialogue.episode %>
  </p>

  <p>
    <strong>Series:</strong>
    <%= dialogue.series %>
  </p>

  <p>
    <strong>Character:</strong>
    <%= dialogue.character %>
  </p>

</div>

app/views/dialogues/_form.html.erb
<%= form_with(model: dialogue) do |form| %>
  <% if dialogue.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(dialogue.errors.count, "error") %> prohibited this dialogue from being saved:</h2>

      <ul>
        <% dialogue.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :line, style: "display: block" %>
    <%= form.text_field :line %>
  </div>

  <div>
    <%= form.label :episode, style: "display: block" %>
    <%= form.text_field :episode %>
  </div>

  <div>
    <%= form.label :series, style: "display: block" %>
    <%= form.text_field :series %>
  </div>

  <div>
    <%= form.label :character, style: "display: block" %>
    <%= form.text_field :character %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/dialogues/edit.html.erb
<h1>Editing dialogue</h1>

<%= render "form", dialogue: @dialogue %>

<br>

<div>
  <%= link_to "Show this dialogue", @dialogue %> |
  <%= link_to "Back to dialogues", dialogues_path %>
</div>

app/views/dialogues/index.html.erb
<p style="color: green"><%= notice %></p>
<div class='heading-section'>
<h2>
   Star Trek Dialogue Search
</h2>
<%=link_to "search using ChatGTP embeddings (TNG only)", episode_texts_path %>
</div>
<%=form_with url: dialogues_path, :method => "get", html: {class: 'search-section'} do |form|%>
    <%=form.label :query, 'Search Dialogue or Character'%>
   <%=form.text_field :query%>
    <%=form.label :dictionary, "Use Dictionary"%>
    <%=form.check_box :dictionary %>

    <%=form.submit "Search"%>
<% end %>
<% if @dialogues.length == 300%>
    Over
<%end%>
<%= @dialogues.length%> Results


<div class='search-results'>
<% @dialogues.each do | dialogue|%>
    <div>
        <h3 class="quote">
           <%=link_to dialogue.line, "#{dialogue_url(dialogue.id)}\##{dialogue.id}"%>
        </h3>
        <div class='author'>
         - <%=dialogue.character%>, <%=dialogue.series%> <%=dialogue.episode%>
        </div>
    </li>
<% end %>
</div>

app/views/dialogues/new.html.erb
<h1>New dialogue</h1>

<%= render "form", dialogue: @dialogue %>

<br>

<div>
  <%= link_to "Back to dialogues", dialogues_path %>
</div>

app/views/dialogues/show.html.erb
<p style="color: green"><%= notice %></p>

<h3><%= @dialogue.line %></h3>
-<%=@dialogue.character%>, <%=@dialogue.series%>, <%=@dialogue.episode%>

<div>
  <%= link_to 'Back', :back %>

  <div class="episode-text">
  <h3> Full Episode Text </h2>
      <%=@with_highlights.html_safe%>
  </div>

app/views/episode_texts/index.html.erb
<p style="color: green"><%= notice %></p>
<div class='heading-section'>
<h2>
   Star Trek Dialogue Search
</h2>
<%=link_to "Search Using Key Words ", dialogues_path %>
</div>
<%=form_with url: episode_texts_path, :method => "get", html: {class: 'search-section'} do %>
    <%=label_tag(:query, 'Search using description: "the enterprise computer becomes sentient"')%>
    <br>
    <%=text_field_tag('query', params[:query])%>
    <%=submit_tag("Search")%>
<% end %>


<div class='search-results'>
<% @results.each do | result|%>
    <div>
        <h3 class="quote">
           <%=link_to result["text"], episode_text_url(result['metadata']['source_id']) %>
        </h3
        <div>
         Score: <%=result['score']%>
        </div>
        </div>
<% end %>
</div>

app/views/episode_texts/show.html.erb
  <%= link_to 'Back', :back %>

  <div class="episode-text">
  <h3> Full Episode Text </h2>
      <%=@episode_text.html_safe%>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuoteSearch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quotes/index.html.erb
<div class='heading-section'>
    <h2>
    Quotes Search ( GoodReads)
    </h2>
    <%=link_to "Search Star Trek Dialogue instead", dialogues_path %>
</div>
<%=form_with url: quotes_path, :method => "get" do |form| %>
    <%=form.label :query, 'Search Quote Or Author'%>
    <%=form.text_field :query)%>
    <%=from.label :dictionary%>
    <%=form.submit "Search"%>
<% end %>

<div class="search-results">
<% @quotes.each do | quote|%>
    <div>
        <h3 class="quote">
           <%=quote.content%> 
        </h3>
        <div class='author'>
         - <%=quote.author%>
        </div>
    </li>
<% end %>

</div>